version: '3.7'

services:
  orchestrator:
    build:
      context: .
      network: host
    container_name: max-orchestrator
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - android-max

  android-max:
    image: budtmo/docker-android:emulator_10.0
    container_name: android-max
    privileged: true
    ports:
      - "6080:6080"
    volumes:
      - ./max.apk:/root/max.apk
      - ./emulator.py:/home/androidusr/docker-android/cli/src/device/emulator.py:ro
    environment:
      - DEVICE=Samsung Galaxy S10
      - APPIUM=false
      - WEB_VNC=true
      - EMULATOR_ARGS=-no-audio -no-boot-anim
